enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Video ads' 'Remove viewer discretion dialog' 'Change header' 'Hide video action buttons' 'Hide end screen suggested video' 'Hide layout components' 'Hide player flyout menu items' 'Hide related video overlay' 'Open videos fullscreen' 'Return YouTube Dislike' 'SponsorBlock' 'Theme' 'GmsCore support' 'Bypass URL redirects' 'Open links externally' 'Loop video' 'Spoof video streams' 'Video quality' 'Playback speed'"
exclusive-patches = true
version = "auto"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[GooglePhotos]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Music-Morphe]
enabled = true
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patcher-args = "-e 'Change package name' -OpackageName=com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "RVX"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Reddit]
enabled = true
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
arch = "arm64-v8a"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Messenger]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
excluded-patches = "'Disable typing indicator'"
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"