enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
remove-rv-integrations-checks = false
parallel-jobs = 1
dpi = "nodpi anydpi 120-640dpi"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
patches-version = "latest"
build-mode = "apk"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Video ads' 'Remove viewer discretion dialog' 'Change header' 'Hide video action buttons' 'Navigation buttons' 'Hide player overlay buttons' 'Hide end screen suggested video' 'Hide layout components' 'Hide player flyout menu items' 'Hide Shorts components' 'Disable sign in to TV popup' 'Exit fullscreen mode' 'Open videos fullscreen' 'Return YouTube Dislike' 'SponsorBlock' 'Disable resuming Shorts on startup' 'Theme' 'Remove background playback restrictions' 'GmsCore support' 'Bypass URL redirects' 'Open links externally' 'Loop video' 'Spoof video streams' 'Video quality' 'Playback speed'"
exclusive-patches = true
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[GooglePhotos]
enabled = true
patches-version = "dev"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Music-Morphe]
enabled = true
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
patches-version = "latest"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = "-e 'Change package name' -OpackageName=com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "RVX"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
enabled = true
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
build-mode = "apk"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Messenger]
enabled = true
patches-version = "dev"
build-mode = "apk"
arch = "arm64-v8a"
excluded-patches = "'Disable typing indicator'"
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"